### ISSUE TITLE
Add support for Deployment, Ingress, and other extended resources

### ISSUE THREAD

**Issue by philidem** [maxmanuylov/terraform-provider-kubernetes#1]
First off, this terraform plugin seems really promising and I think our team would find it helpful with a few enhancements.

Currently, it looks like resources of type [Deployment](https://kubernetes.io/docs/user-guide/deployments/) and [Ingress](https://kubernetes.io/docs/user-guide/ingress/) are not supported.

It looks like this plugins can only manage the built-in api v1 resources with this path pattern:
`/api/v1/namespaces/{namespace}/{collection}`

The new extensions don't have a namespace and follow this path pattern:
`/apis/extensions/v1beta1/{collection}`

See API documentation for extensions here:
https://kubernetes.io/docs/api-reference/extensions/v1beta1/operations/

**Comment by ama2** [comment]
me too
plz support ingress and deproyment

**Comment by maxmanuylov** [comment]
All types of resources are actually supported:

In version 1.3+ you should just use a usual full Deployment config with `apiVersion` and `kind` fields specified.

In older versions you should specify the `api_path = "apis/extensions/v1beta1"` property for your deployment's `kubernetes_resource`. Note that `api_path` has `apis/` prefix here while `apiVersion` field in yaml/json config would be just `extensions/v1beta1`.
