### ISSUE TITLE
Proposal: use provider "kubernetes" and simplify kubernetes_resource

### ISSUE THREAD

**Issue by philidem** [maxmanuylov/terraform-provider-kubernetes#2]
Here are a couple of proposals:

## Use `provider "kubernetes"`

Use `provider "kubernetes"` instead of `data "kubernetes_cluster" "main"`. This would be analogous to the `aws` provider implementation.

I am not sure if the current terraform plugin implementation forces you use to use a `data` object but this was not intuitive to me.

## Simplify `kubernetes_resource`

Only support the following arguments:

- `provider` **OPTIONAL**
  - _provider_ would be analogous to the `aws` provider implementation
  - This argument should be optional and the _default_ kubernetes provider should be used when not supplied.
- `contents` **REQUIRED** (NOTE: _contents_ is more appropriate than _content_ which is currently being used)
  - Unlike the current implementation, I think you should have developers include `apiVersion`, `kind`, and `metadata` attributes just like they were using if they were storing their configuration as files. You could parse the YAML contents and use these values to build the API URL.

I don't have any experience writing Terraform plugins and I haven't used Go very much but maybe we can work together to make these changes if you like this proposal.

**Comment by maxmanuylov** [comment]
Now you can configure either `provider "k8s"` (was renamed due to built-in "kubernetes" provider) or `data "k8s_cluster" "<name>"` which is still needed when your provider configuration is dynamic and depends on another terraform resources.

`k8s_resource` was simplified and both YAML and JSON formats are now supported.
